/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 */
import { MotiaStream } from 'motia'

declare module 'motia' {
  interface Streams {
    chessSidechatMessage: MotiaStream<{ message: string; sender: string; role: 'white' | 'black' | 'spectator' | 'root'; timestamp: number }>
    chessLiveAiGames: MotiaStream<{ id: string; gameId: string; players: { white: { provider: 'openai' | 'gemini' | 'claude' | 'grok'; model: string }; black: { provider: 'openai' | 'gemini' | 'claude' | 'grok'; model: string } }; createdAt: string }>
    chessLeaderboard: MotiaStream<{ id: string; provider: 'openai' | 'gemini' | 'claude' | 'grok'; model: string; gamesPlayed: number; victories: number; checkmates: number; draws: number; endedEarly: number; illegalMoves: number; sumCentipawnScores: number; sumHighestSwing: number }>
    chessGame: MotiaStream<{ id: string; fen: string; turn: 'white' | 'black'; status: 'pending' | 'completed' | 'draw' | 'endedEarly'; lastMove?: Array<string>; lastMoveSan?: string; winner?: 'white' | 'black'; turns?: number; endGameReason?: string; players: { white: { userId?: string; ai?: 'openai' | 'gemini' | 'claude' | 'grok'; model?: string; illegalMoveAttempts?: number; totalMoves?: number; captures?: Array<{ piece: string; score: number }>; promotions?: number }; black: { userId?: string; ai?: 'openai' | 'gemini' | 'claude' | 'grok'; model?: string; illegalMoveAttempts?: number; totalMoves?: number; captures?: Array<{ piece: string; score: number }>; promotions?: number } }; check: boolean; scoreboard?: { white: { averageSwing: number; highestSwing: number; finalCentipawnScore: number; blunders: number; illegalMoveAttempts: number; captures: Array<{ piece: string; score: number }>; promotions: number; checks: number }; black: { averageSwing: number; highestSwing: number; finalCentipawnScore: number; blunders: number; illegalMoveAttempts: number; captures: Array<{ piece: string; score: number }>; promotions: number; checks: number }; totalMoves: number; decisiveMoment?: { moveNumber: number; evaluationSwing: number; move: Array<string>; fen: string } } }>
    chessGameMove: MotiaStream<{ color: 'white' | 'black'; fenBefore: string; fenAfter: string; lastMove: Array<string>; check: boolean; evaluation?: { centipawnScore: number; bestMove: string; evaluationSwing: number; blunder: boolean } }>
    chessGameMessage: MotiaStream<{ id: string; message: string; sender: string; profilePic?: string; role: 'white' | 'black' | 'spectator' | 'root'; timestamp: number; moveSan?: string; isIllegalMove?: boolean }>
  }

  interface Enqueues {}
}
