name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

env:
  # Motia Deploy
  MOTIA_API_KEY: ${{ secrets.MOTIA_API_KEY }}
  MOTIA_PROJECT_ID: 95ec1c16-91e5-4e5f-bcad-87c4c4ba0d42
  MOTIA_ENV_ID: abc37e6f-1095-4446-bc28-f70a93eceb83

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create Env file
        working-directory: api
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
          echo "STOCKFISH_PATH=./../../lib/stockfish" >> .env

      - name: Download Stockfish Binary
        working-directory: api
        run: |
          mkdir -p lib
          curl -L https://github.com/official-stockfish/Stockfish/releases/latest/download/stockfish-ubuntu-x86-64-avx2.tar -o stockfish-source.tar
          tar -xvf stockfish-source.tar
          chmod +x stockfish/stockfish-ubuntu-x86-64-avx2
          mv stockfish/stockfish-ubuntu-x86-64-avx2 lib/stockfish
          rm -rf stockfish-source.tar stockfish

      - name: Motia Install
        working-directory: api
        run: npx motia install

      - name: Activate PyEnv
        working-directory: api
        run: source python_modules/bin/activate

      - name: Deploy using Motia Cloud
        working-directory: api
        run: |
          npx motia cloud deploy \
            --api-key ${{ env.MOTIA_API_KEY }} \
            --project-id ${{ env.MOTIA_PROJECT_ID }} \
            --environment-id ${{ env.MOTIA_ENV_ID }} \
            --version-name ${GITHUB_SHA::7} \
            --env-file .env
