name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'streams-api/**'

env:
  # Application environment variables
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  # Motia Deploy
  MOTIA_API_KEY: ${{ secrets.MOTIA_API_KEY }}
  MOTIA_PROJECT_ID: 572dca96-a142-4f08-b531-c8fff67eb05b
  MOTIA_ENV_ID: 37c5728c-8ec5-4ace-b107-c446841a3c3f

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create Env file
        working-directory: streams-api
        run: |
          echo "OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" > .env
          echo "GEMINI_API_KEY=${{ env.GEMINI_API_KEY }}" > .env
          echo "ANTHROPIC_API_KEY=${{ env.ANTHROPIC_API_KEY }}" > .env

      - name: Deploy using Motia Cloud
        working-directory: streams-api
        run: |
          npx motia cloud deploy \
            --api-key ${{ env.MOTIA_API_KEY }} \
            --project-id ${{ env.MOTIA_PROJECT_ID }} \
            --environment-id ${{ env.MOTIA_ENV_ID }} \
            --version-name ${GITHUB_SHA::7} \
            --env-file .env
